pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }

    parameters {
        string(name: 'ECR_REPO_URL', defaultValue: 'NONE', description: 'AWS ECR Repository HTTP URL')
    }
    stages {
         /* stage('Clone repository') {
            steps {
                script{
                checkout scm
                }
            }
        } */

        stage('Code Build') {
            steps {
                script{
                    dir('ecs/demo-ecs') {
                        sh './gradlew clean build -x test --no-daemon' //run a gradle task
                    }
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                script{
                    dir('ecs/demo-ecs') {
                        app = docker.build("nandeeshsu/demo_ecs")
                    }
                }
            }
        }
        stage('Test'){
            steps {
                 echo 'Empty'
            }
        }
        stage('Deploy') {
            steps {
                script{
                    docker.withRegistry("${params.ECR_REPO_URL}", 'ecr:us-east-1:cloud_user') {
                        app.push("${params.ECR_REPO_URL}/demo_ecs")
                        app.push("latest")
                    }
                }
            }
        }
    }
}