pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
         /* stage('Clone repository') {
            steps {
                script{
                checkout scm
                }
            }
        } */

        stage('Code Build') {
            steps {
                script{
                    dir('ecs/demo-ecs') {
                        sh './gradlew clean build -x test --no-daemon' //run a gradle task
                    }
                }
            }
        }

        stage('Docker Image Build') {
            steps {
                script{
                    dir('ecs/demo-ecs') {
                        app = docker.build("nandeeshsu/demo_ecs")
                    }
                }
            }
        }
        stage('Test'){
            steps {
                 echo 'Empty'
            }
        }
        stage('Deploy') {
            steps {
                script{
                    docker.withRegistry('https://316445831419.dkr.ecr.us-east-1.amazonaws.com/demo_ecs', 'ecr:us-east-1:cloud_user') {
                    app.push("${env.BUILD_NUMBER}")
                    app.push("latest")
                    }
                }
            }
        }
    }
}